from perfect_information_game.heuristics.network import Network
from perfect_information_game.heuristics.proxy_network import ProxyNetwork
from perfect_information_game.heuristics.utils import spawn_training_process, train_from_scratch
