# classes must be imported after their dependencies
from perfect_information_game.games.invalid_move_exception import InvalidMoveException
from perfect_information_game.games.game import Game
from perfect_information_game.games.amazons import Amazons
from perfect_information_game.games.battleship import Battleship
from perfect_information_game.games.checkers import Checkers
from perfect_information_game.games.connect4 import Connect4
from perfect_information_game.games.dots_and_boxes import DotsAndBoxes
from perfect_information_game.games.gomoku import Gomoku
from perfect_information_game.games.multi_tic_tac_toe import MultiTicTacToe
from perfect_information_game.games.othello import Othello
from perfect_information_game.games.tic_tac_toe import TicTacToe
from perfect_information_game.games.chess import Chess
from perfect_information_game.games.king_of_the_hill_chess import KingOfTheHillChess
from perfect_information_game.games.monster_chess import MonsterChess
